### ISSUE TITLE
Seeing ```connect ECONNREFUSED 127.0.0.1:443``` coming from got libary

### ISSUE THREAD

**Issue by laurie-wrisk** [gocardless/gocardless-nodejs#108]
Full error output is below

```
GotError: connect ECONNREFUSED 127.0.0.1:443
    at onError (/Users/laurie/wrisk/runbook/.yarn/cache/got-npm-10.7.0-9215e39e3e-e233703fcf.zip/node_modules/got/dist/source/request-as-event-emitter.js:140:29)
    at handleRequest (/Users/laurie/wrisk/runbook/.yarn/cache/got-npm-10.7.0-9215e39e3e-e233703fcf.zip/node_modules/got/dist/source/request-as-event-emitter.js:173:17)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
  name: 'RequestError',
  code: 'ECONNREFUSED'
}

```
Someone else reported a similar issue coming from this repo at the beginning of the year here: https://github.com/gocardless/gocardless-nodejs/issues/88.  I've asked if they ever found a solution.

Could this be caused by using got version ^10.2.2 (10.7.0 being used)?  Latest version of got is 11.8.2: https://www.npmjs.com/package/got.

**Comment by monossido** [comment]
Same here...
