### ISSUE TITLE
Unprocessable Entity

### ISSUE THREAD

**Issue by ZiggerZZ** [gocardless/gocardless-nodejs#112]
Hello,

Since 20.01.2022 I started getting 'Error: Unprocessable Entity' when calling `client.redirectFlows.create`:
```
    const redirectFlow = await client.redirectFlows.create({
      description: description,
      session_token: session_token,
      success_redirect_url: success_redirect_url,
      prefilled_customer: prefilled_customer,
    });
```

I didn't change anything in the code and it used to work before.

Apparently it is the line `const response = await this.api.request(requestParams);` in `redirectFlowService` that creates the issue.

Any ideas?

**Comment by jjholmes927** [comment]
Hey @ZiggerZZ,

Could you please provide what environment is this in and post the full error message?

**Comment by ZiggerZZ** [comment]
Hi @jjholmes927,
The environment: `constants.Environments.Sandbox`

Full error:
```
Error: Unprocessable Entity
    at Function.buildFromResponse (/Users/ziggerzz/PycharmProjects/backend/node_modules/src/errors.ts:84:16)
    at Api.request (/Users/ziggerzz/PycharmProjects/backend/node_modules/src/api/api.ts:121:47)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at RedirectFlowService.create (/Users/ziggerzz/PycharmProjects/backend/node_modules/src/services/redirectFlowService.ts:92:22)
    at /Users/ziggerzz/PycharmProjects/backend/src/index.ts:668:26
```

**Comment by jjholmes927** [comment]
Hey @ZiggerZZ,

As per our docs here https://developer.gocardless.com/api-reference/#errors-invalid-api-usage-errors, for a 422 the response body should contain detail on what request params are deemed invalid. Try having a look at those and see what you find

**Comment by ZiggerZZ** [comment]
I updated gocardless to v2.3.0 and the error is gone :)
