### ISSUE TITLE
Cannot deploy on Firebase Cloud Functions

### ISSUE THREAD

**Issue by coosmiyn** [gocardless/gocardless-nodejs#73]
Hello! I am using Firebase Cloud Functions and I want to integrate it with the API, but when I try to deploy my functions, I get an error.

The only thing I've added was the

`const gocardless = require("gocardless-nodejs");`

and it returns an error

`Detailed stack trace: /srv/node_modules/got/dist/source/create.js:101
    got.paginate = async function* (url, options) {
                                 ^

SyntaxError: Unexpected token *
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/srv/node_modules/got/dist/source/index.js:7:18)`

I am using:

Firebase Functions: 3.6.1
GoCardless: 1.1.2
Node: 12.13.0

**Comment by coosmiyn** [comment]
Oh, yes, found the problem. I do have node 12.13.0 but Firebase Functions were still set to 8. Updating it to 10 solved the problem. Now I feel really stupid.
