### ISSUE TITLE
All fields on GoCardlessException are private

### ISSUE THREAD

**Issue by aharin** [gocardless/gocardless-nodejs#92]
Using typescript, when GoCardlessException is raised, how does one figure out what is the cause of this exception as all fields on GoCardlessException are private? Also GoCardlessException does not seem to have toString or toJson implemented, while JSON.stringify(exception) fails with 

```{
    "errorType": "TypeError",
    "errorMessage": "Converting circular structure to JSON\n    --> starting at object with constructor 'TLSSocket'\n    |     property '_httpMessage' -> object with constructor 'ClientRequest'\n    --- property 'socket' closes the circle",
    "stack": [
        "TypeError: Converting circular structure to JSON",
        "    --> starting at object with constructor 'TLSSocket'",
        "    |     property '_httpMessage' -> object with constructor 'ClientRequest'",
        "    --- property 'socket' closes the circle",
        "    at JSON.stringify (<anonymous>)",
        "    at GoCardlessException.gocardless_nodejs_GoCardlessException__WEBPACK_IMPORTED_MODULE_5__.GoCardlessException.toString (/var/task/dist/lambda.js:3041:17)",
        "    at new Error (<anonymous>)",
        "    at _homogeneousError (/var/runtime/CallbackContext.js:12:12)",
        "    at postError (/var/runtime/CallbackContext.js:29:54)",
        "    at done (/var/runtime/CallbackContext.js:56:7)",
        "    at fail (/var/runtime/CallbackContext.js:68:7)",
        "    at /var/runtime/CallbackContext.js:104:16"
    ]
}
```

**Comment by danwakefield** [comment]
Thanks for the report.
I'll make some changes so the errors in this library more closely resemble those in our Python library and you can access all of the fields 

https://github.com/gocardless/gocardless-pro-python/blob/master/gocardless_pro/errors.py

**Comment by danwakefield** [comment]
This should be fixed in https://github.com/gocardless/gocardless-nodejs/releases/tag/v2.1.0
we reworked how the errors worked and exposed the attributes.
